@FitTrek.API_HostAddress = https://localhost:7279


GET {{FitTrek.API_HostAddress}}/api/nutritionists

###

DELETE {{FitTrek.API_HostAddress}}/api/nutritionists/3

###

GET {{FitTrek.API_HostAddress}}/api/Nutritionists/3

###

GET {{FitTrek.API_HostAddress}}/api/nutritionists

###
